spring.application.name=notification-service

eventuatelocal.kafka.bootstrap.servers=localhost:9092
eventuatelocal.zookeeper.connection.string=localhost:2181

server.port=8084

logging.level.io.eventuate=INFO
logging.level.io.eventuate.examples.tram.ordersandcustomers=DEBUG
