dependencies {
  implementation project(":payment-service:payment-service-domain")
  implementation "io.eventuate.tram.core:eventuate-tram-spring-events-starter"
  implementation "io.eventuate.tram.core:eventuate-tram-spring-optimistic-locking"
  implementation "io.eventuate.tram.core:eventuate-tram-spring-jdbc-kafka"
  implementation "io.eventuate.tram.core:eventuate-tram-spring-flyway"
  runtimeOnly "org.flywaydb:flyway-database-postgresql"
  runtimeOnly "org.flywaydb:flyway-sqlserver:$flywayVersion"
}
